### ISSUE TITLE
While JoinMeeting getting this issue

### ISSUE THREAD

**Issue by amit-uipep** [lennhv/jitsi_meet_plugin#6]
JitsiMeetingOptions: JitsiMeetingOptions{room: plugintestroom, serverURL: https://meet.jit.si, subject: My Plugin Test Meeting, token: null, audioMuted: true, audioOnly: true, videoMuted: true, userDisplayName: Plugin Test User, userEmail: fake@email.com, iosAppBarRGBAColor :#0080FF80, featureFlags: {FeatureFlagEnum.WELCOME_PAGE_ENABLED: false} }
===================================== Join meeting
listener Instance of 'JitsiMeetingListener'
webOptions {"roomName":"plugintestroom","width":"100%","height":"100%","enableWelcomePage":false,"chromeExtensionBanner":null,"userInfo":{"displayName":"Plugin Test User"}}
serverUrl meet.jit.si before calling jisi meet api
{"roomName":"plugintestroom","width":"100%","height":"100%","enableWelcomePage":false,"chromeExtensionBanner":null,"userInfo":{"displayName":"Plugin Test User"}}
TypeError: Cannot read property 'shadowRoot' of undefined
    at new JitsiMeetAPI (<anonymous>:12:80)
    at jitsi_meet_web.JitsiMeetPlugin.__.joinMeeting (http://localhost:63772/packages/jitsi_meet_web/jitsi_meet_web.dart.lib.js:133:20)
    at joinMeeting.next (<anonymous>)
    at runBody (http://localhost:63772/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:63772/dart_sdk.js:39083:7)
    at jitsi_meet_web.JitsiMeetPlugin.__.joinMeeting (http://localhost:63772/packages/jitsi_meet_web/jitsi_meet_web.dart.lib.js:125:20)
    at joinMeeting (http://localhost:63772/packages/jitsi_meet/jitsi_meet.dart.lib.js:59:79)
    at joinMeeting.next (<anonymous>)
    at runBody (http://localhost:63772/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:63772/dart_sdk.js:39083:7)
    at Function.joinMeeting (http://localhost:63772/packages/jitsi_meet/jitsi_meet.dart.lib.js:49:20)
    at main._MeetingState.new._joinMeeting (http://localhost:63772/packages/jitsi_meet_example/main.dart.lib.js:1503:36)
    at _joinMeeting.next (<anonymous>)
    at runBody (http://localhost:63772/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:63772/dart_sdk.js:39083:7)
    at main._MeetingState.new.[_joinMeeting] (http://localhost:63772/packages/jitsi_meet_example/main.dart.lib.js:1474:20)
    at http://localhost:63772/packages/jitsi_meet_example/main.dart.lib.js:1455:37
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:63772/packages/flutter/src/material/icon_button.dart.lib.js:50511:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:63772/packages/flutter/src/gestures/recognizer.dart.lib.js:203:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:63772/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:63772/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:63772/packages/flutter/src/gestures/tap.dart.lib.js:199:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:63772/packages/flutter/src/gestures/arena.dart.lib.js:222:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:63772/packages/flutter/src/gestures/binding.dart.lib.js:335:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:63772/packages/flutter/src/gestures/binding.dart.lib.js:314:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:63772/packages/flutter/src/rendering/layer.dart.lib.js:6087:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:63772/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:63772/packages/flutter/src/gestures/binding.dart.lib.js:258:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:63772/packages/flutter/src/gestures/binding.dart.lib.js:247:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:63772/packages/flutter/src/gestures/binding.dart.lib.js:237:65)
    at Object.invoke1 (http://localhost:63772/dart_sdk.js:183773:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:63772/dart_sdk.js:164269:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:63772/dart_sdk.js:164903:49)
    at http://localhost:63772/dart_sdk.js:165355:26
    at http://localhost:63772/dart_sdk.js:165308:16
    at http://localhost:63772/dart_sdk.js:165007:11

**Comment by abnerh69** [comment]
Hi, same issue here.  Any solution? workaround?
Maybe Flutter version?   I am using:

Flutter 1.27.0-8.0.pre • channel unknown • unknown source
Framework • revision b7d4806243 (6 weeks ago) • 2021-02-19 09:22:45 -0800
Engine • revision 6993cb229b
Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)
